# Generated by Django 6.0.5 on 2026-05-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_user_alter_like_user_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post'),
        ),
    ]
